### ISSUE TITLE
where is the srcipt to eval_synthbio_templates.py?

### ISSUE THREAD

**Issue by yuulin** [Tiiiger/templm#1]
A great work! 
Where is the srcipt to eval_synthbio_templates.py?

**Comment by Tiiiger** [comment]
Hey

seems like I forgot to clean and upload those. I will do that today.

**Comment by Tiiiger** [comment]
https://github.com/Tiiiger/templm/blob/main/scripts/synthbio/refine.sh#L30

nevermind I just put those together in this script.
